artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/mlruns/0/a7a29d54b3e54f3ca32c25b190700c8d/artifacts
end_time: 1780759101280
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a7a29d54b3e54f3ca32c25b190700c8d
run_name: nebulous-jay-876
run_uuid: a7a29d54b3e54f3ca32c25b190700c8d
source_name: ''
source_type: 4
source_version: ''
start_time: 1780759086007
status: 3
tags: []
user_id: runner
